updates

diff --git a/bin/capstrace b/bin/capstrace
--- a/bin/capstrace
+++ b/bin/capstrace
@@ -149,7 +149,8 @@ _strace () {
 
   output="${OUTPUT_DIR}/$(date "+%F-%T")-$1-strace";
 
-  strace -fTrvs200000 -o "$output" -p"$1" &
+  (strace -fTrvs200000 -o "$output" -p"$1" 2> /dev/null \
+    || echo "Failed to attach" >> "$output") &
 
   str_pid="$!"
 
@@ -158,7 +159,7 @@ _strace () {
 
   # Kill strace once php process becomes idle
   while(true); do
-    if tail | grep -qE "accept\(0| \+\+\+ killed by"; then
+    if tail | grep -qE "accept\(0| \+\+\+ killed by|Failed to attach"; then
       kill "$str_pid" 2>/dev/null || echo "$1 exited abnormally";
       break;
     fi
