updates

diff --git a/bin/nkdrupal b/bin/nkdrupal
--- a/bin/nkdrupal
+++ b/bin/nkdrupal
@@ -5,8 +5,18 @@
 readonly ARGS="$*"
 readonly ARGA=("$@")
 
+readonly AWK='/bin/awk'
+readonly CAT='/bin/cat'
+readonly CUT='/bin/cut'
+readonly FIND='/bin/find'
+readonly GREP='/bin/grep'
+readonly MYSQL='/usr/bin/mysql'
+readonly SED='/bin/sed'
+readonly STAT='/usr/bin/stat'
+readonly TAIL='/usr/bin/tail'
+
 _usage() {
-  cat <<- EOF
+  "$CAT" <<- EOF
   This is the usage
 EOF
 }
@@ -29,49 +39,49 @@ main () {
 
   config="${sitepath}/sites/default/settings.php"
 
-  [[ -f ${config} ]] || (echo -e "\nCould not find Drupal install at ${sitepath}\n"; return 1);
+  [[ -f ${config} ]] || (echo -e "\nCould not "$FIND" Drupal install at ${sitepath}\n"; return 1);
 
   # Version Information
-  if grep -q "define('VERSION'" ${sitepath}/modules/system/system.module; then
+  if "$GREP" -q "define('VERSION'" ${sitepath}/modules/system/system.module; then
     verfile="${sitepath}/modules/system/system.module"
-  elif grep -q "define('VERSION'" ${sitepath}/includes/bootstrap.inc; then
+  elif "$GREP" -q "define('VERSION'" ${sitepath}/includes/bootstrap.inc; then
     verfile="${sitepath}/includes/bootstrap.inc"
   fi;
 
-  version=$(grep "define('VERSION'" $verfile | cut -d\' -f4)
-  installdate=$(stat $verfile | awk '/Change/ {print $2,$3}' | cut -d. -f1)
+  version=$("$GREP" "define('VERSION'" $verfile | "$CUT" -d\' -f4)
+  installdate=$("$STAT" $verfile | "$AWK" '/Change/ {print $2,$3}' | "$CUT" -d. -f1)
 
   # Database Config (7.x)
   # Database, Username, Password, Host, Driver, Prefix
   if [[ $version =~ ^7 || $version =~ ^8 ]]; then
 
-    dbname=$(awk '($1 ~ /database/ && $3 !~ /array/) {print $3}' $config | cut -d\' -f2)
-    dbuser=$(awk '($1 ~ /username/) {print $3}' $config | cut -d\' -f2)
-    dbpass=$(awk '($1 ~ /password/) {print $3}' $config | cut -d\' -f2)
-    dbhost=$(awk '($1 ~ /host/) {print $3}' $config | cut -d\' -f2)
-    dbdriv=$(awk '($1 ~ /driver/) {print $3}' $config | cut -d\' -f2)
-    prefix=$(awk '($1 ~ /prefix/) {print $3}' $config | cut -d\' -f2)
+    dbname=$("$AWK" '($1 ~ /database/ && $3 !~ /array/) {print $3}' $config | "$CUT" -d\' -f2)
+    dbuser=$("$AWK" '($1 ~ /username/) {print $3}' $config | "$CUT" -d\' -f2)
+    dbpass=$("$AWK" '($1 ~ /password/) {print $3}' $config | "$CUT" -d\' -f2)
+    dbhost=$("$AWK" '($1 ~ /host/) {print $3}' $config | "$CUT" -d\' -f2)
+    dbdriv=$("$AWK" '($1 ~ /driver/) {print $3}' $config | "$CUT" -d\' -f2)
+    prefix=$("$AWK" '($1 ~ /prefix/) {print $3}' $config | "$CUT" -d\' -f2)
 
     # Database Config (6.x)
     # mysql://username:password@localhost/database
   elif [[ $version =~ ^6 || $version =~ ^5 ]]; then
 
-    dbase=$(awk '($1 ~ /db_url/) {print $3}' $config | cut -d\' -f2)
-    dbname=$(echo "$dbase" | cut -d@ -f2 | cut -d/ -f2)
-    dbuser=$(echo "$dbase" | cut -d: -f2 | cut -d/ -f3)
-    dbpass=$(echo "$dbase" | cut -d: -f3 | cut -d@ -f1)
-    dbhost=$(echo "$dbase" | cut -d@ -f2 | cut -d/ -f1)
-    dbdriv=$(echo "$dbase" | cut -d: -f1)
-    prefix=$(awk '($1 ~ /db_prefix/) {print $3}' $config | cut -d\' -f2)
+    dbase=$("$AWK" '($1 ~ /db_url/) {print $3}' $config | "$CUT" -d\' -f2)
+    dbname=$(echo "$dbase" | "$CUT" -d@ -f2 | "$CUT" -d/ -f2)
+    dbuser=$(echo "$dbase" | "$CUT" -d: -f2 | "$CUT" -d/ -f3)
+    dbpass=$(echo "$dbase" | "$CUT" -d: -f3 | "$CUT" -d@ -f1)
+    dbhost=$(echo "$dbase" | "$CUT" -d@ -f2 | "$CUT" -d/ -f1)
+    dbdriv=$(echo "$dbase" | "$CUT" -d: -f1)
+    prefix=$("$AWK" '($1 ~ /db_prefix/) {print $3}' $config | "$CUT" -d\' -f2)
 
   fi
 
   database="${dbdriv}://${dbuser}:${dbpass}@${dbhost}/${dbname}$(if [[ -n ${prefix} ]]; then echo ."${prefix}"*; fi)"
 
   base_path=$(cd $sitepath || return; pwd -P;)
-  base_url=$(cd $sitepath || return; pwd -P | sed 's:/chroot::g;s:/html::g' | cut -d/ -f4-)
-  sitename=$(mysql -u "$dbuser" -p"$dbpass" "$dbname" -h "$dbhost" -e "select name,value from ${prefix}variable where name=\"site_name\";" | tail -1 | cut -d\" -f2)
-  posts=$(mysql -u "$dbuser" -p"$dbpass" "$dbname" -h "$dbhost" -e "select count(*) from ${prefix}node;" | tail -1)
+  base_url=$(cd $sitepath || return; pwd -P | "$SED" 's:/chroot::g;s:/html::g' | "$CUT" -d/ -f4-)
+  sitename=$("$MYSQL" -u "$dbuser" -p"$dbpass" "$dbname" -h "$dbhost" -e "select name,value from ${prefix}variable where name=\"site_name\";" | "$TAIL" -1 | "$CUT" -d\" -f2)
+  posts=$("$MYSQL" -u "$dbuser" -p"$dbpass" "$dbname" -h "$dbhost" -e "select count(*) from ${prefix}node;" | "$TAIL" -1)
 
   echo;
   printf "%-18s: %s\n" "Base Path" "${base_path}"
diff --git a/bin/nkjoomla b/bin/nkjoomla
--- a/bin/nkjoomla
+++ b/bin/nkjoomla
@@ -5,13 +5,29 @@
 readonly ARGS="$*"
 readonly ARGA=("$@")
 
+readonly AWK='/bin/awk'
+readonly CUT='/bin/cut'
+readonly DATE='/bin/date'
+readonly FIND='/bin/find'
+readonly GREP='/bin/grep'
+readonly GZIP='/bin/gzip';
+readonly MYSQL='/usr/bin/mysql'
+readonly RM='/bin/rm'
+readonly RM='/bin/rm --preserve-root'
+readonly SED='/bin/sed'
+readonly SLEEP='/bin/sleep'
+readonly SORT='/bin/sort'
+readonly STAT='/usr/bin/stat'
+readonly TAIL='/usr/bin/tail'
+
+
 _joomlausage(){
   echo " Usage: nkjoomla [path] OPTION [query]
   -B | --backup .... Backup the Joomla database as the user
   -c | --clear ..... Clear Joomla cache
   -C | --cache ..... Enable/Disable cache
   -e | --execute ... Execute a custom query (use '*' and \\\")
-  -g | --gzip ...... Enable/Disable gzip compression
+  -g | --gzip ...... Enable/Disable "$GZIP" compression
   -i | --info ...... Display user credentials for database
   -l | --login ..... Log into database using user credentials
   -P | --password .. Update or reset password for a user
@@ -24,26 +40,26 @@ _joomlausage(){
 _joomlainfo(){
   # Output collected information
   printf "%-18s: %s\n" "Base Path" "$(cd "$SITEPATH" || return; pwd -P)"
-  printf "%-18s: %s\n" "Product Name" "$(grep 'const PRODUCT' "$VERFILE" | cut -d\' -f2) \"$CODENAME\""
-  printf "%-18s: %s\n" "Site Title" "$(grep '$sitename ' "$CONFIG" | cut -d\' -f2)"
-  printf "%-18s: %s\n" "Install Date" "$(stat "$VERFILE" | awk '/Change/ {print $2,$3}' | cut -d. -f1)"
-  printf "%-18s: %s\n" "Encryption Key" "$(grep '$secret' "$CONFIG" | cut -d\' -f2)"
+  printf "%-18s: %s\n" "Product Name" "$("$GREP" 'const PRODUCT' "$VERFILE" | "$CUT" -d\' -f2) \"$CODENAME\""
+  printf "%-18s: %s\n" "Site Title" "$("$GREP" '$sitename ' "$CONFIG" | "$CUT" -d\' -f2)"
+  printf "%-18s: %s\n" "Install Date" "$("$STAT" "$VERFILE" | "$AWK" '/Change/ {print $2,$3}' | "$CUT" -d. -f1)"
+  printf "%-18s: %s\n" "Encryption Key" "$("$GREP" '$secret' "$CONFIG" | "$CUT" -d\' -f2)"
   printf "%-18s: %s\n" "Version (Date)" "$VERSION"
-  printf "%-18s: %s\n" "Front End URL" "http://$(cd "$SITEPATH" || return; pwd -P | sed 's:^/chroot::' | cut -d/ -f4- | sed 's:/html::')/"
-  printf "%-18s: %s\n" "Back End URL" "http://$(cd "$SITEPATH" || return; pwd -P | sed 's:^/chroot::' | cut -d/ -f4- | sed 's:/html::')/administrator"
-  printf "%-18s: %s\n" "Return-Path Email" "$(grep '$mailfrom' "$CONFIG" | cut -d\' -f2)"
-  printf "%-18s: %s\n" "Gzip Compression" "$(grep '$gzip' "$CONFIG" | cut -d\' -f2 | sed 's/0/Disabled/;s/1/Enabled/')"
+  printf "%-18s: %s\n" "Front End URL" "http://$(cd "$SITEPATH" || return; pwd -P | "$SED" 's:^/chroot::' | "$CUT" -d/ -f4- | "$SED" 's:/html::')/"
+  printf "%-18s: %s\n" "Back End URL" "http://$(cd "$SITEPATH" || return; pwd -P | "$SED" 's:^/chroot::' | "$CUT" -d/ -f4- | "$SED" 's:/html::')/administrator"
+  printf "%-18s: %s\n" "Return-Path Email" "$("$GREP" '$mailfrom' "$CONFIG" | "$CUT" -d\' -f2)"
+  printf "%-18s: %s\n" "Gzip Compression" "$("$GREP" '$gzip' "$CONFIG" | "$CUT" -d\' -f2 | "$SED" 's/0/Disabled/;s/1/Enabled/')"
   printf "%-18s: %s\n" "DB Connection" "$dbtype://$dbuser:$dbpass@$dbhost/$dbname$(if [[ -n $prefix ]]; then echo ."$prefix*"; fi)"
-  printf "%-18s: %s\n" "Session Method" "$(grep '$session' "$CONFIG" | cut -d\' -f2)"
-  printf "%-18s: %s\n" "Cache Method" "$(grep '$cache_handler' "$CONFIG" | cut -d\' -f2) / $(grep '$caching' "$CONFIG" | cut -d\' -f2 | sed -e 's/.*0.*/Disabled/' -e 's/.*1.*/Enabled/')"
+  printf "%-18s: %s\n" "Session Method" "$("$GREP" '$session' "$CONFIG" | "$CUT" -d\' -f2)"
+  printf "%-18s: %s\n" "Cache Method" "$("$GREP" '$cache_handler' "$CONFIG" | "$CUT" -d\' -f2) / $("$GREP" '$caching' "$CONFIG" | "$CUT" -d\' -f2 | "$SED" -e 's/.*0.*/Disabled/' -e 's/.*1.*/Enabled/')"
   echo;
 
   ## Show installed: components, modules, plugins, and templates
   for x in {Component,Module,Plugin,Template}; do
     printf "%-18s: " "Active ${x}s";
-    mysql -u"$dbuser" -p"$dbpass" -h "$dbhost" "$dbname" \
+    "$MYSQL" -u"$dbuser" -p"$dbpass" -h "$dbhost" "$dbname" \
       -e "select name,type from ${prefix}extensions where type like \"$x\" and enabled = 1;" 2> /dev/null \
-      | grep -Ev 'name.*type|^plg' | sed 's/ /_/g' | sort | uniq | awk '{printf "%s, ",$1}' | sed 's/, $//';
+      | "$GREP" -Ev 'name.*type|^plg' | "$SED" 's/ /_/g' | "$SORT" | uniq | "$AWK" '{printf "%s, ",$1}' | "$SED" 's/, $//';
     echo;
     echo;
   done;
@@ -56,7 +72,7 @@ _joomlasum(){
 _joomlaconnect(){
   if [[ $runonce -eq 0 ]]; then
     _joomlasum; runonce=1;
-  fi && mysql -u "$dbuser" -p"$dbpass" -h "$dbhost" "$dbname" -e "$@";
+  fi && "$MYSQL" -u "$dbuser" -p"$dbpass" -h "$dbhost" "$dbname" -e "$@";
 }
 
 _joomlabackup(){
@@ -71,10 +87,10 @@ _joomlabackup(){
   echo "Using: mysqldump --opt --skip-lock-tables -u'$dbuser' -p'$dbpass' -h $dbhost $dbname";
   if [[ -f /usr/bin/pv ]]; then
     mysqldump --opt --skip-lock-tables -u"$dbuser" -p"dbpass" -h "$dbhost" "$dbname" \
-      | pv -N 'MySQL-Dump' | $COMPRESS --fast | pv -N 'Compression' > "${dbname}"-"$(date +%Y.%m.%d-%H.%M)".sql.gz;
+      | pv -N 'MySQL-Dump' | $COMPRESS --fast | pv -N 'Compression' > "${dbname}"-"$("$DATE" +%Y.%m.%d-%H.%M)".sql.gz;
   else
     mysqldump --opt --skip-lock-tables -u"$dbuser" -p"$dbpass" -h "$dbhost" "$dbname" \
-      | $COMPRESS --fast > "${dbname}"-"$(date +%Y.%m.%d-%H.%M)".sql.gz;
+      | $COMPRESS --fast > "${dbname}"-"$("$DATE" +%Y.%m.%d-%H.%M)".sql.gz;
   fi;
 }
 
@@ -109,15 +125,15 @@ main () {
   CONFIG="$SITEPATH/configuration.php"
 
   # Check if there is a Joomla install here (sanity check)
-  [[ -f "$CONFIG" ]] || (echo -e "Could not find Joomla install at $SITEPATH\n"; return 1)
+  [[ -f "$CONFIG" ]] || (echo -e "Could not "$FIND" Joomla install at $SITEPATH\n"; return 1)
 
   # Gather DB Connection info
-  dbtype=$(grep '$dbtype ' "$CONFIG" | cut -d\' -f2)
-  dbhost=$(grep '$host ' "$CONFIG" | cut -d\' -f2)
-  dbuser=$(grep '$user ' "$CONFIG" | cut -d\' -f2)
-  dbpass=$(grep '$password ' "$CONFIG" | cut -d\' -f2)
-  dbname=$(grep '$db ' "$CONFIG" | cut -d\' -f2)
-  prefix=$(grep '$dbprefix ' "$CONFIG" | cut -d\' -f2)
+  dbtype=$("$GREP" '$dbtype ' "$CONFIG" | "$CUT" -d\' -f2)
+  dbhost=$("$GREP" '$host ' "$CONFIG" | "$CUT" -d\' -f2)
+  dbuser=$("$GREP" '$user ' "$CONFIG" | "$CUT" -d\' -f2)
+  dbpass=$("$GREP" '$password ' "$CONFIG" | "$CUT" -d\' -f2)
+  dbname=$("$GREP" '$db ' "$CONFIG" | "$CUT" -d\' -f2)
+  prefix=$("$GREP" '$dbprefix ' "$CONFIG" | "$CUT" -d\' -f2)
 
   # Check location of version file
   if [[ -f "$SITEPATH/libraries/cms/version/version.php" ]]; then
@@ -127,12 +143,12 @@ main () {
   fi
 
   # Gather version information
-  RELEASE="$(grep 'const RELEASE' "$VERFILE" | cut -d\' -f2)";
-  DEV_LEVEL="$(grep 'const DEV_LEVEL' "$VERFILE" | cut -d\' -f2)";
-  DEV_STATUS="$(grep 'const DEV_STATUS' "$VERFILE" | cut -d\' -f2)";
-  BUILD="$(grep 'const BUILD' "$VERFILE" | cut -d\' -f2)";
-  RELDATE="$(grep 'const RELDATE' "$VERFILE" | cut -d\' -f2)";
-  CODENAME="$(grep 'const CODENAME' "$VERFILE" | cut -d\' -f2)";
+  RELEASE="$("$GREP" 'const RELEASE' "$VERFILE" | "$CUT" -d\' -f2)";
+  DEV_LEVEL="$("$GREP" 'const DEV_LEVEL' "$VERFILE" | "$CUT" -d\' -f2)";
+  DEV_STATUS="$("$GREP" 'const DEV_STATUS' "$VERFILE" | "$CUT" -d\' -f2)";
+  BUILD="$("$GREP" 'const BUILD' "$VERFILE" | "$CUT" -d\' -f2)";
+  RELDATE="$("$GREP" 'const RELDATE' "$VERFILE" | "$CUT" -d\' -f2)";
+  CODENAME="$("$GREP" 'const CODENAME' "$VERFILE" | "$CUT" -d\' -f2)";
   VERSION="$RELEASE.$DEV_LEVEL $DEV_STATUS ($RELDATE) $BUILD";
 
 
@@ -142,17 +158,17 @@ main () {
     -c|--clear)
       cd "$SITEPATH"/cache/ || return 1;
       for x in */; do
-        echo "Clearing $x Cache" | sed 's:/::';
-        find "$x" -type f -exec rm {} \;;
+        echo "Clearing $x Cache" | "$SED" 's:/::';
+        "$FIND" "$x" -type f -exec "$RM" {} \;;
       done;
       cd - &> /dev/null || return;
       ;;
     -C|--cache)
-      if grep -q "caching = '0'" "$CONFIG" 2> /dev/null; then
-        sed -i "s/caching = '0'/caching = '1'/" "$CONFIG";
+      if "$GREP" -q "caching = '0'" "$CONFIG" 2> /dev/null; then
+        "$SED" -i "s/caching = '0'/caching = '1'/" "$CONFIG";
         echo "Caching is ${BRIGHT}${GREEN}Enabled${NORMAL}";
       else
-        sed -i "s/caching = '1'/caching = '0'/" "$CONFIG";
+        "$SED" -i "s/caching = '1'/caching = '0'/" "$CONFIG";
         echo "Caching is ${BRIGHT}${GREEN}Disabled${NORMAL}";
       fi;
       ;;
@@ -160,25 +176,25 @@ main () {
       _joomlaconnect "${param};";
       ;;
     -g|--gzip)
-      if grep -q "gzip = '0'" "$CONFIG" 2> /dev/null; then
-        sed -i "s/gzip = '0'/gzip = '1'/" "$CONFIG";
+      if "$GREP" -q "gzip = '0'" "$CONFIG" 2> /dev/null; then
+        "$SED" -i "s/gzip = '0'/gzip = '1'/" "$CONFIG";
         echo "Gzip is ${BRIGHT}${GREEN}Enabled${NORMAL}";
       else
-        sed -i "s/gzip = '1'/gzip = '0'/g" "$CONFIG";
+        "$SED" -i "s/gzip = '1'/gzip = '0'/g" "$CONFIG";
         echo "Gzip is ${BRIGHT}${GREEN}Disabled${NORMAL}";
       fi
       ;;
     -i|--info)
       echo "Database Connection Info:";
-      echo -e "\nLoc.Conn: mysql -u'$dbuser' -p'$dbpass' $dbname -h $dbhost \nRem.Conn: mysql -u'$dbuser' -p'$dbpass' $dbname -h $(hostname)\n";
+      echo -e "\nLoc.Conn: "$MYSQL" -u'$dbuser' -p'$dbpass' $dbname -h $dbhost \nRem.Conn: "$MYSQL" -u'$dbuser' -p'$dbpass' $dbname -h $(hostname)\n";
       echo -e "Username: $dbuser \nPassword: $dbpass \nDatabase: $dbname $(if [[ -n $prefix ]]; then echo \\nPrefix..: "$prefix"; fi) \nLoc.Host: $dbhost \nRem.Host: $(hostname)";
       ;;
-    -l|--login) mysql -u "$dbuser" -p"$dbpass" -h "$dbhost" "$dbname";
+    -l|--login) "$MYSQL" -u "$dbuser" -p"$dbpass" -h "$dbhost" "$dbname";
       ;;
     -P|--password)
       if [[ -n $param ]]; then
-        username=$(echo "$param" | awk '{print $1}');
-        password=$(echo "$param" | awk '{print $2}');
+        username=$(echo "$param" | "$AWK" '{print $1}');
+        password=$(echo "$param" | "$AWK" '{print $2}');
         _joomlaconnect "UPDATE ${prefix}users SET password = MD5(\"${password}\") WHERE ${prefix}users.username = \"$username\";"
         echo -e "New Joomla Login Credentials:\nUsername: $username\nPassword: $password"
       elif [[ -z $param || $param == '-h' || $param == '--help' ]]; then
@@ -186,14 +202,14 @@ main () {
       fi
       ;;
     -s|--swap)
-      username=$(_joomlaconnect "SELECT username FROM ${prefix}users ORDER BY id LIMIT 1;" | tail -1)
-      password=$(_joomlaconnect "SELECT password FROM ${prefix}users ORDER BY id LIMIT 1;" | tail -1 | sed 's/\$/\\\$/g')
+      username=$(_joomlaconnect "SELECT username FROM ${prefix}users ORDER BY id LIMIT 1;" | "$TAIL" -1)
+      password=$(_joomlaconnect "SELECT password FROM ${prefix}users ORDER BY id LIMIT 1;" | "$TAIL" -1 | "$SED" 's/\$/\\\$/g')
       _joomlaconnect "UPDATE ${prefix}users SET password=MD5('nexpassword') ORDER BY id LIMIT 1";
       echo -e "You have 20 seconds to login using the following credentials\n"
-      echo -e "LoginURL: http://$(cd "$SITEPATH" || return; pwd -P | sed "s:^/chroot::" | cut -d/ -f4- | sed 's:html/::')/administrator"
+      echo -e "LoginURL: http://$(cd "$SITEPATH" || return; pwd -P | "$SED" "s:^/chroot::" | "$CUT" -d/ -f4- | "$SED" 's:html/::')/administrator"
       echo -e "Username: $username\nPassword: nexpassword\n"
       for x in {1..20}; do
-        sleep 1;
+        "$SLEEP" 1;
         printf ". ";
       done;
       echo
