updates

diff --git a/bin/nkjoomla b/bin/nkjoomla
--- a/bin/nkjoomla
+++ b/bin/nkjoomla
@@ -22,19 +22,23 @@ readonly TAIL='/usr/bin/tail'
 
 
 _joomlausage(){
-  echo " Usage: nkjoomla [path] OPTION [query]
+  cac <<- EOF
+
+  Usage: nkjoomla [path] OPTION [query]
   -B | --backup .... Backup the Joomla database as the user
   -c | --clear ..... Clear Joomla cache
   -C | --cache ..... Enable/Disable cache
-  -e | --execute ... Execute a custom query (use '*' and \\\")
-  -g | --gzip ...... Enable/Disable "$GZIP" compression
+  -e | --execute ... Execute a custom query (use '*' and \\")
+  -g | --gzip ...... Enable/Disable $GZIP compression
   -i | --info ...... Display user credentials for database
   -l | --login ..... Log into database using user credentials
   -P | --password .. Update or reset password for a user
   -s | --swap ...... Temporarily swap out user password
   -u | --users ..... Show users configured within the database
   -h | --help ....... Display this help and quit
-  When run with no options, returns summary information";
+  When run with no options, returns summary information
+
+EOF
 }
 
 _joomlainfo(){
@@ -125,7 +129,7 @@ main () {
   CONFIG="$SITEPATH/configuration.php"
 
   # Check if there is a Joomla install here (sanity check)
-  [[ -f "$CONFIG" ]] || (echo -e "Could not "$FIND" Joomla install at $SITEPATH\n"; return 1)
+  [[ -f "$CONFIG" ]] || (echo -e "Could not $FIND Joomla install at $SITEPATH\n"; return 1)
 
   # Gather DB Connection info
   dbtype=$("$GREP" '$dbtype ' "$CONFIG" | "$CUT" -d\' -f2)
@@ -186,7 +190,7 @@ main () {
       ;;
     -i|--info)
       echo "Database Connection Info:";
-      echo -e "\nLoc.Conn: "$MYSQL" -u'$dbuser' -p'$dbpass' $dbname -h $dbhost \nRem.Conn: "$MYSQL" -u'$dbuser' -p'$dbpass' $dbname -h $(hostname)\n";
+      echo -e "\nLoc.Conn: $MYSQL -u'$dbuser' -p'$dbpass' $dbname -h $dbhost \nRem.Conn: $MYSQL -u'$dbuser' -p'$dbpass' $dbname -h $(hostname)\n";
       echo -e "Username: $dbuser \nPassword: $dbpass \nDatabase: $dbname $(if [[ -n $prefix ]]; then echo \\nPrefix..: "$prefix"; fi) \nLoc.Host: $dbhost \nRem.Host: $(hostname)";
       ;;
     -l|--login) "$MYSQL" -u "$dbuser" -p"$dbpass" -h "$dbhost" "$dbname";
